// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/info/ethics.tsx";
import * as $3 from "./routes/info/index.tsx";
import * as $4 from "./routes/info/reflection.tsx";
import * as $5 from "./routes/projects/test.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/info/ethics.tsx": $2,
    "./routes/info/index.tsx": $3,
    "./routes/info/reflection.tsx": $4,
    "./routes/projects/test.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
